# Generated by Django 4.2.28 on 2026-08-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import GO.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0208_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_original', models.FileField(upload_to=GO.models.assinatura_usuario_upload_to)),
                ('imagem_processada', models.ImageField(upload_to=GO.models.assinatura_usuario_imagem_upload_to)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_rdo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura de usuário',
                'verbose_name_plural': 'Assinaturas de usuários',
            },
        ),
    ]
