# Generated by Django 4.2.28 on 2026-08-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0208_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordChangeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_password_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change Status',
                'verbose_name_plural': 'Password Change Statuses',
            },
        ),
    ]
