# Generated by Django 4.2.28 on 2026-08-13 12:24

import GO.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0210_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPropostaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=GO.models.anexo_proposta_comercial_upload_to)),
                ('nome_original', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_propostas_comerciais_enviados', to=settings.AUTH_USER_MODEL)),
                ('financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='GO.financeiro')),
            ],
            options={
                'verbose_name': 'anexo de proposta comercial',
                'verbose_name_plural': 'anexos de propostas comerciais',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
