# Generated by Django 4.2.28 on 2026-08-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0211_anexo_proposta_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecriticaoportunidade',
            name='iremos_participar',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True),
        ),
    ]
