# Generated by Django 4.2.28 on 2026-08-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0209_userpasswordchangestatus'),
        ('GO', '0212_adicionar_pergunta_participacao_analise_critica'),
    ]

    operations = [
    ]
