# Generated by Django 4.2.28 on 2026-08-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0213_merge_20260817_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaDocumentoRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_revisao', models.PositiveIntegerField()),
                ('tipo_documento', models.CharField(default='PC_OFFSHORE', max_length=30)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTA', 'Pronta'), ('GERADA', 'Gerada')], default='RASCUNHO', max_length=15)),
                ('introducao_objetivo', models.TextField(blank=True, default='')),
                ('procedimento_titulo', models.CharField(blank=True, default='', max_length=255)),
                ('premissas_confirmadas', models.BooleanField(default=False)),
                ('obrigacoes_confirmadas', models.BooleanField(default=False)),
                ('procedimento_confirmado', models.BooleanField(default=False)),
                ('equipe_confirmada', models.BooleanField(default=False)),
                ('equipamentos_confirmados', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_proposta_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_proposta_criados', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_revisados', to='GO.financeiro')),
            ],
            options={
                'ordering': ('-numero_revisao', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PropostaDocumentoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCEDIMENTO', 'Procedimento'), ('EQUIPE', 'Equipe'), ('EQUIPAMENTO', 'Equipamento'), ('PREMISSA', 'Premissa'), ('OBRIGACAO', 'Obrigação')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField()),
                ('quantidade', models.CharField(blank=True, default='', max_length=50)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='GO.propostadocumentorevisao')),
            ],
            options={
                'ordering': ('tipo', 'ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PropostaDocumentoFinanceiroSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=150)),
                ('unidade', models.CharField(blank=True, default='', max_length=50)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_snapshot', to='GO.propostadocumentorevisao')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='propostadocumentorevisao',
            constraint=models.UniqueConstraint(fields=('proposta', 'numero_revisao', 'tipo_documento'), name='unique_documento_revisao_tipo'),
        ),
    ]
