# Generated by Django 4.2.28 on 2026-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0214_propostadocumentorevisao_propostadocumentolinha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostadocumentorevisao',
            name='conteudo_revisao',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
