# Generated by Django 4.2.28 on 2026-08-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0215_onshore_document_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostadocumentorevisao',
            name='revisao_documental',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
