# Generated by Django 4.2.28 on 2026-08-20 12:50

import GO.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0216_document_revision_per_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_data', models.CharField(max_length=100)),
                ('projeto', models.CharField(blank=True, default='', max_length=150)),
                ('servico_concluido', models.TextField(blank=True, default='')),
                ('servico_em_andamento', models.TextField(blank=True, default='')),
                ('orientacoes_observacoes', models.TextField(blank=True, default='')),
                ('itens_equipamentos', models.JSONField(default=GO.models.default_handover_items)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GO.cliente')),
                ('supervisor_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_criados', to=settings.AUTH_USER_MODEL)),
                ('supervisor_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_recebidos', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GO.unidade')),
            ],
            options={
                'verbose_name': 'Passagem de Serviço',
                'verbose_name_plural': 'Passagens de Serviço',
                'ordering': ['-criado_em'],
            },
        ),
    ]
