# Generated by Django 4.2.28 on 2026-08-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0217_supervisorhandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorhandover',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='GO.ordemservico'),
        ),
    ]
