# Generated by Django 4.2.28 on 2026-08-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0218_financeiro_historico_identidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_clientes', to='GO.ordemservico'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='fonte_lead',
            field=models.CharField(blank=True, choices=[('Portal Group', 'Portal Group'), ('Vendas Ambipar', 'Vendas Ambipar'), ('Cross Shell', 'Cross Shell'), ('Convite Direto', 'Convite Direto'), ('Prospecção Ativa', 'Prospecção Ativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='natureza',
            field=models.CharField(blank=True, choices=[('Aditivo', 'Aditivo'), ('Reajuste', 'Reajuste'), ('Spot', 'Spot'), ('Contrato Novo', 'Contrato Novo'), ('Renovação', 'Renovação')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='segmento_cliente',
            field=models.CharField(blank=True, choices=[('Açúcar e Álcool', 'Açúcar e Álcool'), ('Administração Pública e Relacionados', 'Administração Pública e Relacionados'), ('Agronegócio', 'Agronegócio'), ('Água', 'Água'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Artes, cultura, esporte e recreação', 'Artes, cultura, esporte e recreação'), ('Atacado e Varejo', 'Atacado e Varejo'), ('Atividades administrativas e Relacionados', 'Atividades administrativas e Relacionados'), ('Atividades imobiliárias', 'Atividades imobiliárias'), ('Automotivo, Aviação e Peças', 'Automotivo, Aviação e Peças'), ('Cimentícias', 'Cimentícias'), ('Comunicação', 'Comunicação'), ('Concessionárias', 'Concessionárias'), ('Condomínio', 'Condomínio'), ('Construção e Engenharia', 'Construção e Engenharia'), ('Consultoria e Atividades Profissionais', 'Consultoria e Atividades Profissionais'), ('Data Center', 'Data Center'), ('Educação e Ensino', 'Educação e Ensino'), ('Eletroeletrônica', 'Eletroeletrônica'), ('Embalagens', 'Embalagens'), ('Embarcações e Apoio', 'Embarcações e Apoio'), ('Energia', 'Energia'), ('Eventos', 'Eventos'), ('Fábrica', 'Fábrica'), ('Farmacêutica/Saúde', 'Farmacêutica/Saúde'), ('Ferrovias', 'Ferrovias'), ('Fertilizantes', 'Fertilizantes'), ('Gestão Ambiental', 'Gestão Ambiental'), ('Higiene/Cosméticos', 'Higiene/Cosméticos'), ('Hospitalar e Serviços Humanos', 'Hospitalar e Serviços Humanos'), ('Hoteis/Pousadas', 'Hoteis/Pousadas'), ('Informação e comunicação', 'Informação e comunicação'), ('Infraestrutura', 'Infraestrutura'), ('Instituições Financeiras', 'Instituições Financeiras'), ('Locadora', 'Locadora'), ('Logística', 'Logística'), ('Madeira', 'Madeira'), ('Manutenção e Reparação', 'Manutenção e Reparação'), ('Máquinas e Equipamentos', 'Máquinas e Equipamentos'), ('Material de construção', 'Material de construção'), ('Metal Mecânica/Metalurgia/Siderurgia', 'Metal Mecânica/Metalurgia/Siderurgia'), ('Mineração', 'Mineração'), ('Organismos Internacionais', 'Organismos Internacionais'), ('Organizações sem Fins Lucrativos', 'Organizações sem Fins Lucrativos'), ('Outras atividades de serviços', 'Outras atividades de serviços'), ('Outros', 'Outros'), ('Papel e Celulose', 'Papel e Celulose'), ('Petróleo e Gás', 'Petróleo e Gás'), ('Plásticos e Borracha', 'Plásticos e Borracha'), ('Portos e Terminais', 'Portos e Terminais'), ('Postos de combustível', 'Postos de combustível'), ('Química e Petroquímica', 'Química e Petroquímica'), ('Saneamento/Resíduos', 'Saneamento/Resíduos'), ('Seguradoras', 'Seguradoras'), ('Serviços Ambientais', 'Serviços Ambientais'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Serviços Pessoais', 'Serviços Pessoais'), ('Telecomunicações', 'Telecomunicações'), ('Têxtil, Couro e Vestuário', 'Têxtil, Couro e Vestuário'), ('Transporte Marítimo, Navegação ou Aquaviário', 'Transporte Marítimo, Navegação ou Aquaviário'), ('Transportes e Logística', 'Transportes e Logística'), ('Vidro', 'Vidro'), ('Marítmo', 'Marítmo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='status_proposta',
            field=models.CharField(blank=True, choices=[('Sem Retorno', 'Sem Retorno'), ('Em Análise', 'Em Análise'), ('ShortList', 'ShortList'), ('Revisada', 'Revisada'), ('Perdida/Recusada', 'Perdida/Recusada'), ('Fechada/Contratada', 'Fechada/Contratada'), ('Cancelada', 'Cancelada'), ('Em Elaboração', 'Em Elaboração'), ('Declínio', 'Declínio'), ('Avaliando escopo', 'Avaliando escopo'), ('Aguardando aprovação gestores', 'Aguardando aprovação gestores'), ('Enviada', 'Enviada'), ('Em Negociação', 'Em Negociação')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=10, null=True),
        ),
    ]
