# Generated by Django 4.2.28 on 2026-08-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0218_supervisorhandover_ordem_servico'),
        ('GO', '0219_financeiro_historico_campos'),
    ]

    operations = [
    ]
