# Generated by Django 4.2.28 on 2026-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0220_merge_20260821_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswordchangestatus',
            name='password_change_counter',
            field=models.IntegerField(default=2),
        ),
    ]
