# Generated by Django 4.2.28 on 2026-08-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0220_merge_20260821_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorhandover',
            name='ordem_servico',
        ),
    ]
