# Generated by Django 4.2.28 on 2026-08-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0221_remove_supervisorhandover_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavelcoordenador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_coordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvaliacaoSupervisorMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_nome_snapshot', models.CharField(max_length=150)),
                ('nota', models.CharField(choices=[('OTIMO', 'ÓTIMO'), ('BOM', 'BOM'), ('REGULAR', 'REGULAR'), ('RUIM', 'RUIM'), ('PESSIMO', 'PÉSSIMO')], max_length=20)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('avaliado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_de_supervisores_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_supervisor', to='GO.ordemservico')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_como_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de supervisor da movimentação',
                'verbose_name_plural': 'Avaliações de supervisores das movimentações',
                'ordering': ['-avaliado_em', '-id'],
            },
        ),
    ]
