# Generated by Django 4.2.28 on 2026-08-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0221_remove_supervisorhandover_ordem_servico'),
        ('GO', '0221_userpasswordchangestatus_password_change_counter'),
    ]

    operations = [
    ]
