# Generated by Django 4.2.28 on 2026-08-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0222_merge_20260826_1941'),
        ('GO', '0222_responsavelcoordenador_usuario_and_more'),
    ]

    operations = [
    ]
