# Generated by Django 4.2.28 on 2026-08-28 12:27

import GO.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0223_merge_20260828_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaDocumentoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=GO.models.proposta_documento_imagem_upload_to)),
                ('nome_original', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='GO.propostadocumentorevisao')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_revisao_proposta_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagem de revisão documental',
                'verbose_name_plural': 'imagens de revisão documental',
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
