# Generated by Django 4.2.28 on 2026-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0224_proposta_documento_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('SUPERVISOR IRATA', 'SUPERVISOR IRATA'), ('ELETRICISTA', 'ELETRICISTA'), ('TÉCNICO DE SEGURANÇA', 'TÉCNICO DE SEGURANÇA'), ('AJUDANTE', 'AJUDANTE'), ('RESGATISTA', 'RESGATISTA'), ('MECÂNICO', 'MECÂNICO'), ('N1 IRATA', 'N1 IRATA'), ('N2 IRATA', 'N2 IRATA'), ('N3 IRATA', 'N3 IRATA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='planejamentoequipemembro',
            name='funcao_planejada',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('SUPERVISOR IRATA', 'SUPERVISOR IRATA'), ('ELETRICISTA', 'ELETRICISTA'), ('TÉCNICO DE SEGURANÇA', 'TÉCNICO DE SEGURANÇA'), ('AJUDANTE', 'AJUDANTE'), ('RESGATISTA', 'RESGATISTA'), ('MECÂNICO', 'MECÂNICO'), ('N1 IRATA', 'N1 IRATA'), ('N2 IRATA', 'N2 IRATA'), ('N3 IRATA', 'N3 IRATA')], max_length=100),
        ),
    ]
