# Generated by Django 4.2.28 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0225_alter_pessoa_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='ambiente_operacional',
            field=models.CharField(
                blank=True,
                choices=[('Onshore', 'Onshore'), ('Offshore', 'Offshore')],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
    ]
