# Generated by Django 4.2.28 on 2026-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0229_supervisorhandover_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
