# Generated by Django 4.2.28 on 2026-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0230_cadastro_master_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
