# Generated by Django 4.2.28 on 2026-09-14 18:45

from django.db import migrations, models


FUNCOES_INICIAIS = [
    'SUPERVISOR', 'SUPERVISOR IRATA', 'ELETRICISTA', 'TÉCNICO DE SEGURANÇA',
    'AJUDANTE', 'RESGATISTA', 'MECÂNICO', 'N1 IRATA', 'N2 IRATA', 'N3 IRATA',
]


def preparar_catalogo_gerenciavel(apps, schema_editor):
    Funcao = apps.get_model('GO', 'Funcao')
    # Mantém o catálogo legado para auditoria, sem deixá-lo disponível em novos choices.
    Funcao.objects.all().update(ativo=False)
    for nome in FUNCOES_INICIAIS:
        funcao, _ = Funcao.objects.get_or_create(nome=nome)
        if not funcao.ativo:
            funcao.ativo = True
            funcao.save(update_fields=['ativo'])


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0231_funcao_ativa'),
    ]

    operations = [
        migrations.RunPython(preparar_catalogo_gerenciavel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planejamentoequipemembro',
            name='funcao_planejada',
            field=models.CharField(max_length=100),
        ),
    ]
