# Generated by Django 4.2.28 on 2026-09-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0230_alter_ordemservico_servico_alter_rdo_servico_rdo'),
        ('GO', '0232_funcoes_catalogo_gerenciavel'),
    ]

    operations = [
    ]
