# Generated by Django 4.2.28 on 2026-09-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0233_merge_20260914_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='volume_tanque_exec',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='financeiro_volume_tanques_exec',
                to='GO.rdotanque',
            ),
        ),
    ]
