# Generated by Django 4.2.28 on 2026-09-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0234_financeiro_volume_tanque_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='volume_tanque_exec',
        ),
    ]
